In [1]:
# -*- coding:utf-8 -*-
"""
@file name  : lesson-02.py
@author     : TingsongYu https://github.com/TingsongYu
@date       : 2018-08-26
@brief      : 张量的创建
"""
import torch
import numpy as np
torch.manual_seed(1)
flag = True

# 1. 通过torch.tensor创建张量

In [2]:
# ===============================  example 1 ===============================
if flag:
    arr = np.ones((3, 3))
    print("ndarray的数据类型：", arr.dtype)
    if torch.cuda.is_available():
        t = torch.tensor(arr, device='cuda')
    else:
        t = torch.tensor(arr)

    print(t)


ndarray的数据类型： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


# 2. 通过torch.from_numpy创建张量

In [3]:
# ===============================  example 2 ===============================
if flag:
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    t = torch.from_numpy(arr)
    # print("numpy array: ", arr)
    # print("tensor : ", t)

    # print("\n修改arr")
    # arr[0, 0] = 0
    # print("numpy array: ", arr)
    # print("tensor : ", t)

    print("\n修改tensor")
    t[0, 0] = -1
    print("\nnumpy array: ")
    print(arr)
    print("\ntensor : ")
    print(t)




修改tensor

numpy array: 
[[-1  2  3]
 [ 4  5  6]]

tensor : 
tensor([[-1,  2,  3],
        [ 4,  5,  6]])


# 3. 通过torch.zeros创建张量

In [4]:
# ===============================  example 3 ===============================
if flag:
    out_t = torch.tensor([1])

    t = torch.zeros((3, 3), out=out_t)

    print(t, '\n', out_t)
    print(id(t), id(out_t), id(t) == id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
140609010023736 140609010023736 True


# 4. 通过torch.full创建全1张量

In [5]:
# ===============================  example 4 ===============================
if flag:
    t = torch.full((3, 3), 1)
    print(t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


# 5. 通过torch.arange创建等差数列张量

In [6]:
# ===============================  example 5 ===============================
if flag:
    t = torch.arange(2, 10, 2)
    print(t)

tensor([2, 4, 6, 8])


# 6. 通过torch.linspace创建均分数列张量

In [7]:
# ===============================  example 6 ===============================
if flag:
    # t = torch.linspace(2, 10, 5)
    t = torch.linspace(2, 10, 6)
    print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


# 7. 通过torch.normal创建正态分布张量

In [8]:
# ===============================  example 7 ===============================
if flag:
    # mean：张量 std: 张量
    # mean = torch.arange(1, 5, dtype=torch.float)
    # std = torch.arange(1, 5, dtype=torch.float)
    # t_normal = torch.normal(mean, std)
    # print("mean:{}\nstd:{}".format(mean, std))
    # print(t_normal)

    # mean：标量 std: 标量
    # t_normal = torch.normal(0., 1., size=(4,))
    # print(t_normal)

    # mean：张量 std: 标量
    mean = torch.arange(1, 5, dtype=torch.float)
    std = 1
    t_normal = torch.normal(mean, std)
    print("mean:{}\nstd:{}".format(mean, std))
    print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:1
tensor([1.6614, 2.2669, 3.0617, 4.6213])
