<a href="https://colab.research.google.com/github/wanpingDou/Pytorch-Camp/blob/master/hello%20pytorch/lesson_jupyter/03_tensor_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch中张量的操作：拼接、切分、索引、变换和运算

---
其他：

- torch.t：变换
> 功能：2维张量转置，对矩阵而言，等价于torch.transpose(input, 0, 1)

- torch.manual_seed(1)：[利用随机数种子来使pytorch中的结果可以复现](https://cloud.tencent.com/developer/article/1149041)


In [1]:
# -*- coding:utf-8 -*-
"""
@file name  : lesson-03.py
@author     : TingsongYu https://github.com/TingsongYu
@date       : 2018-08-26
@brief      : 张量操作
"""

import torch
torch.manual_seed(1)
flag = True


## 1. 拼接：cat

> - torch.cat：拼接
  - dim：按照某一维度拼接


In [2]:
# ======================================= example 1 =======================================
# torch.cat

if flag:
    t = torch.ones((2, 3))

    t_0 = torch.cat([t, t], dim=0)
    t_1 = torch.cat([t, t, t], dim=1)
    
    print("t:\n{} shape:{}\n\nt_0:\n{} shape:{}\n\nt_1:\n{} shape:{}".format(t, t.shape, 
                                          t_0, t_0.shape, 
                                          t_1, t_1.shape))



t:
tensor([[1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([2, 3])

t_0:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([4, 3])

t_1:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]) shape:torch.Size([2, 9])


## 2. 拼接：stack
> - [pytorch函数学习随笔记录---stack与cat](https://zhuanlan.zhihu.com/p/70035580)
  - torch.cat会按照dim的维度进行拼接
  - torch.stack会按照dim新增一维，然后跟cat一样拼接

In [3]:
# ======================================= example 2 =======================================
# torch.stack

if flag:
    t = torch.ones((2, 3))

    t_stack0 = torch.stack([t, t], dim=0)

    t_stack1 = torch.stack([t, t], dim=1)

    print("\nt:\n{} shape:{}\n\nt_stack0:\n{} shape:{}\n\nt_stack1:\n{} shape:{}".format(t, t.shape,
                                                t_stack0, t_stack0.shape,
                                                t_stack1, t_stack1.shape))




t:
tensor([[1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([2, 3])

t_stack0:
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) shape:torch.Size([2, 2, 3])

t_stack1:
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) shape:torch.Size([2, 2, 3])


## 3. 切分：chunk
- torch.chunk：切分
> 功能：`将张量按维度dim进行平均切分`
>
> 返回值：`张量列表`
  - input：要切分的张量
  - chunks：要切分的份数
  - dim：要切分的维度

In [4]:
# ======================================= example 3 =======================================
# torch.chunk

if flag:
    a = torch.ones((2, 7))  # 7
    list_of_tensors = torch.chunk(a, dim=1, chunks=3)   # 3

    for idx, t in enumerate(list_of_tensors):
        print("第{}个张量：\n{}, shape is {}\n".format(idx+1, t, t.shape))

第1个张量：
tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])

第2个张量：
tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])

第3个张量：
tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])




## 4. 切分：split
- torch.split：切分
> 功能：`将张量按维度dim进行切分`
>
> 返回值：`张量列表`
  - split_size_or_sections：为int时，表示每一份的长度；为list时，按list元素切分
  - dim : 要切分的维度

In [5]:
# ======================================= example 4 =======================================
# torch.split

if flag: 
    print('==================== split_size_or_sections为整数时：==================== ')
    t = torch.ones((2, 5))
    list_of_tensors = torch.split(t, 2, dim=1)  # [2 , 1, 2]
    for idx, t in enumerate(list_of_tensors):
        print("第{}个张量：\n{}, shape is {}\n".format(idx, t, t.shape))

    print('==================== split_size_or_sections为list时：==================== ')
    t = torch.ones((2, 5))
    list_of_tensors = torch.split(t, [2, 1, 2], dim=1)
    for idx, t in enumerate(list_of_tensors):
        print("第{}个张量：\n{}, shape is {}\n".format(idx, t, t.shape))

==================== split_size_or_sections为整数时：==================== 
第0个张量：
tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])

第1个张量：
tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])

第2个张量：
tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])

==================== split_size_or_sections为list时：==================== 
第0个张量：
tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])

第1个张量：
tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])

第2个张量：
tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])



## 5. 索引：index_select
- torch.index_select：索引
> 功能：`在维度dim上，按index索引数据`
>
> 返回值：`索引得到的数据拼接的张量`
  - input：要索引的张量
  - dim：要索引的维度
  - index：要索引数据的序号，注意dtype是torch.long

In [6]:
# ======================================= example 5 =======================================
# torch.index_select

if flag:
    t = torch.randint(0, 9, size=(3, 3))
    idx = torch.tensor([0, 2], dtype=torch.long)    # float
    t_select = torch.index_select(t, dim=0, index=idx)
    print("t:\n{}\nt_select:\n{}".format(t, t_select))

t:
tensor([[4, 5, 0],
        [5, 7, 1],
        [2, 5, 8]])
t_select:
tensor([[4, 5, 0],
        [2, 5, 8]])


## 6. 索引：masked_select
- torch.masked_select：索引
> 功能：`按mask中的True进行索引`
> 
> 返回值：`一维张量`
  - input：要索引的张量
  - mask：与input同形状的布尔类型张量

In [7]:
# ======================================= example 6 =======================================
# torch.masked_select

if flag:
    t = torch.randint(0, 9, size=(3, 3))
    mask = t.le(5)  # ge is mean greater than or equal/   gt: greater than  le  lt
    t_select = torch.masked_select(t, mask)
    print("t:\n{}\nmask:\n{}\nt_select:\n{} ".format(t, mask, t_select))

t:
tensor([[0, 2, 3],
        [1, 8, 4],
        [0, 3, 6]])
mask:
tensor([[ True,  True,  True],
        [ True, False,  True],
        [ True,  True, False]])
t_select:
tensor([0, 2, 3, 1, 4, 0, 3]) 


## 7. 变换：reshape
- torch.reshape：变换
> 功能：`改变张量形状`
> 
> 注意事项：当张量在内存中是连续的时，新张量与input共享数据内存。这种共享与out不同，out是整个tensor都共享内存，相当于别名；reshape是仅data共享内存。改变一个张量的数据，另一个张量会跟着改变。
  - input：要变换的张量
  - shape：新张量的形状
.data和.detach函数备注：.data 和.detach只取出本体tensor数据，舍弃了grad，grad_fn等额外反向图计算过程需保存的额外信息。- .data取出本体tensor后仍与原数据共享内存，在使用in-place操作后，会修改原数据的值，而如果在反向传播过程中使用到原数据会导致计算错误。- .detach，如果在反向传播过程中发现原数据被修改过会报错，更加安全

In [8]:
# ======================================= example 7 =======================================
# torch.reshape

if flag:
    t = torch.randperm(8)  # torch.randperm(n, out=None):给定参数n，返回一个从0到n-1的随机整数排列 
    t_reshape = torch.reshape(t, (-1, 2, 2))    # -1
    print("t:{}\nt_reshape:\n{}".format(t, t_reshape))

    t[0] = 1024
    print("t:{}\nt_reshape:\n{}".format(t, t_reshape))
    print("t.data 内存地址:{}".format(id(t.data)))
    print("t_reshape.data 内存地址:{}".format(id(t_reshape.data)))

t:tensor([2, 0, 1, 6, 3, 4, 7, 5])
t_reshape:
tensor([[[2, 0],
         [1, 6]],

        [[3, 4],
         [7, 5]]])
t:tensor([1024,    0,    1,    6,    3,    4,    7,    5])
t_reshape:
tensor([[[1024,    0],
         [   1,    6]],

        [[   3,    4],
         [   7,    5]]])
t.data 内存地址:140384043357960
t_reshape.data 内存地址:140384043357960


## 8. 变换：transpose
- torch.transpose：变换
> 功能：交换张量的两个维度。在图像的预处理中，有时读取的图像数据是(c, h, w)，但是我们常用的是(h, w, c)，就需要用此方法把channel和width交换，然后width和height交换
  - input：要变换的张量
  - dim0：要交换的维度
  - dim1：要交换的维度

In [9]:
# ======================================= example 8 =======================================
# torch.transpose

if flag:
    # torch.transpose
    t = torch.rand((2, 3, 4))
    t_transpose = torch.transpose(t, dim0=1, dim1=2)    # c*h*w     h*w*c
    print("t shape:{}\nt_transpose shape: {}".format(t.shape, t_transpose.shape))

t shape:torch.Size([2, 3, 4])
t_transpose shape: torch.Size([2, 4, 3])


## 9. 压缩：squeeze
- torch.squeeze：压缩
> 功能：压缩长度为1的维度（轴）
  - dim：若为None，移除所有长度为1的轴；若指定维度，当且仅当该轴长度为1时，可以被移除

In [10]:
# ======================================= example 9 =======================================
# torch.squeeze

if flag:
    t = torch.rand((1, 2, 3, 1))
    t_sq = torch.squeeze(t)
    t_0 = torch.squeeze(t, dim=0)
    t_1 = torch.squeeze(t, dim=1)
    print(t.shape)
    print(t_sq.shape)
    print(t_0.shape)
    print(t_1.shape)

torch.Size([1, 2, 3, 1])
torch.Size([2, 3])
torch.Size([2, 3, 1])
torch.Size([1, 2, 3, 1])


## 10. 拓展：unsqueeze
- torch.unsqueeze：拓展
> 功能：依据dim扩展维度
  - dim: 扩展的维度。必须指定，否则会报错。

In [11]:
# ======================================= example 10 =======================================
# torch.squeeze

if flag:
    t = torch.rand((1, 2, 3, 1))
    t_0 = torch.unsqueeze(t, dim=0)
    t_1 = torch.unsqueeze(t, dim=1)
    print(t.shape)
    print(t_0.shape)
    print(t_1.shape)

torch.Size([1, 2, 3, 1])
torch.Size([1, 1, 2, 3, 1])
torch.Size([1, 1, 2, 3, 1])


## 11. 运算

- add(input, other, *, alpha=1, out=None)
    
$$ \text{out} = \text{input} + \text{alpha} \times \text{other} $$

In [12]:
# ======================================= example 11 =======================================
# torch.add

if flag:
    t_0 = torch.randn((3, 3))
    t_1 = torch.ones_like(t_0)
    t_add = torch.add(input=t_0, alpha=10, other=t_1)

    print("t_0:\n{}\nt_1:\n{}\nt_add_10:\n{}".format(t_0, t_1, t_add))


t_0:
tensor([[-1.0273, -0.7286, -0.7209],
        [ 1.1115,  0.1889,  0.3040],
        [ 0.2830,  2.0379,  0.1633]])
t_1:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t_add_10:
tensor([[ 8.9727,  9.2714,  9.2791],
        [11.1115, 10.1889, 10.3040],
        [10.2830, 12.0379, 10.1633]])
